from __future__ import annotations

INCIDENT_MARKED_LOST = 'INCIDENT_MARKED_LOST'
INCIDENT_CONFIRMED_STOLEN = 'INCIDENT_CONFIRMED_STOLEN'
INCIDENT_REMOTE_LOCK_DECISION = 'INCIDENT_REMOTE_LOCK_DECISION'
INCIDENT_REMOTE_WIPE_DELAYED = 'INCIDENT_REMOTE_WIPE_DELAYED'
INCIDENT_REMOTE_WIPE_EXECUTED = 'INCIDENT_REMOTE_WIPE_EXECUTED'
INCIDENT_RECOVERED = 'INCIDENT_RECOVERED'
INCIDENT_CANCELLED = 'INCIDENT_CANCELLED'
INCIDENT_DECOMMISSIONED = 'INCIDENT_DECOMMISSIONED'
