package com.example.trackme.domain.incident

object IncidentAuditEvents {
    const val INCIDENT_MARKED_LOST = "INCIDENT_MARKED_LOST"
    const val INCIDENT_CONFIRMED_STOLEN = "INCIDENT_CONFIRMED_STOLEN"
    const val INCIDENT_RECOVERED = "INCIDENT_RECOVERED"
    const val INCIDENT_CANCELLED = "INCIDENT_CANCELLED"
    const val INCIDENT_DECOMMISSIONED = "INCIDENT_DECOMMISSIONED"
    const val INCIDENT_REMOTE_LOCK_DECISION = "INCIDENT_REMOTE_LOCK_DECISION"
    const val INCIDENT_REMOTE_WIPE_DELAYED = "INCIDENT_REMOTE_WIPE_DELAYED"
    const val INCIDENT_REMOTE_WIPE_EXECUTED = "INCIDENT_REMOTE_WIPE_EXECUTED"
    const val INCIDENT_REMOTE_WIPE_FAILED = "INCIDENT_REMOTE_WIPE_FAILED"
    const val INCIDENT_NOTIFICATION_ESCALATION = "INCIDENT_NOTIFICATION_ESCALATION"
}
